##########################################

 The client you need to connect is called:
 looking-glass-client

 Please do isntall the driver found in:
 /opt/LookingGlass/windows/driver/

 Then Install the host application:
 /opt/LookingGlass/windows/host

 You may also want to install the VirtIO
 drivers in your windows guest.
 It's not required but I recommend it.


##########################################
